"""Authoritative catalog of manageable RockHawk settings."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


MODEL_ROLES = (
    "orchestrator",
    "triage",
    "extraction",
    "qc",
    "synthesis",
    "embeddings",
)

ROLE_LABELS = {
    "orchestrator": "Orchestrator",
    "triage": "Triage",
    "extraction": "Coding / extraction",
    "qc": "QC",
    "synthesis": "Synthesis",
    "embeddings": "Embeddings",
}


@dataclass(frozen=True)
class SettingDef:
    key: str
    category: str
    category_label: str
    label: str
    description: str
    value_type: str
    default: Any
    risk: str
    editability: str
    restart_required: bool = False
    secret: bool = False
    enum_options: tuple[str, ...] | None = None
    floor: Any = None
    env_key: str | None = None
    env_mode: str = "pin"
    todo: bool = False
    tags: tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        return {
            "key": self.key,
            "category": self.category,
            "category_label": self.category_label,
            "label": self.label,
            "description": self.description,
            "value_type": self.value_type,
            "default": None if self.secret else self.default,
            "risk": self.risk,
            "editability": self.editability,
            "restart_required": self.restart_required,
            "secret": self.secret,
            "enum_options": list(self.enum_options) if self.enum_options else None,
            "floor": self.floor,
            "env_key": self.env_key,
            "env_mode": self.env_mode,
            "todo": self.todo,
            "tags": list(self.tags),
        }


def _s(**kwargs: Any) -> SettingDef:
    return SettingDef(**kwargs)


SETTINGS: tuple[SettingDef, ...] = (
    _s(
        key="app.product_name",
        category="application",
        category_label="1. Application & branding",
        label="Product name",
        description="Name shown in the UI chrome and OpenAPI title fallback.",
        value_type="string",
        default="RockHawk Review Tables",
        risk="low",
        editability="editable",
        env_key="APP_NAME",
        tags=("branding",),
    ),
    _s(
        key="app.support_email",
        category="application",
        category_label="1. Application & branding",
        label="Support contact",
        description="Low-risk operator contact shown in the Administration Center.",
        value_type="string",
        default="admin@rockhawk.local",
        risk="low",
        editability="editable",
        tags=("branding", "vertical-slice"),
    ),
    _s(
        key="app.banner_text",
        category="application",
        category_label="1. Application & branding",
        label="Workspace banner",
        description="Optional banner under the product name. Presentation only.",
        value_type="string",
        default="Attorney assistance only. Verify every cell before reliance.",
        risk="low",
        editability="editable",
        tags=("branding",),
    ),
    _s(
        key="ai.provider",
        category="ai",
        category_label="2. AI providers & model roles",
        label="AI provider",
        description="mock stays on-box. openai_compatible talks to Open WebUI or any /v1 endpoint. Admin can switch unless ROCKHAWK_PIN_AI_SETTINGS is set.",
        value_type="enum",
        default="mock",
        risk="high",
        editability="confirm",
        enum_options=("mock", "openai_compatible"),
        env_key="AI_PROVIDER",
        env_mode="fallback",
        tags=("ai",),
    ),
    _s(
        key="ai.openai_compatible.base_url",
        category="ai",
        category_label="2. AI providers & model roles",
        label="Open WebUI / OpenAI-compatible base URL",
        description="Open WebUI / vLLM / Ollama /v1 root (example: http://host.docker.internal:8080/v1). Test Connection never sends matter documents.",
        value_type="string",
        default="http://host.docker.internal:8080/v1",
        risk="medium",
        editability="editable",
        env_key="OPENAI_COMPATIBLE_BASE_URL",
        env_mode="fallback",
        tags=("ai",),
    ),
    _s(
        key="ai.openai_compatible.api_key",
        category="ai",
        category_label="2. AI providers & model roles",
        label="Provider API key",
        description="Stored only as a secret reference. GET/diff/audit/export show configured vs not configured, never the raw key.",
        value_type="secret",
        default="",
        risk="high",
        editability="confirm",
        secret=True,
        env_key="OPENAI_COMPATIBLE_API_KEY",
        env_mode="fallback",
        tags=("ai", "secret"),
    ),
    _s(
        key="ai.openai_compatible.model",
        category="ai",
        category_label="2. AI providers & model roles",
        label="Default chat model",
        description="Fallback model when a role has no independent assignment. Pick from Discover models or type an id.",
        value_type="string",
        default="llama3.1",
        risk="medium",
        editability="editable",
        env_key="OPENAI_COMPATIBLE_MODEL",
        env_mode="fallback",
        tags=("ai",),
    ),
    *[
        _s(
            key=f"ai.role.{role}",
            category="ai",
            category_label="2. AI providers & model roles",
            label=f"{ROLE_LABELS[role]} model",
            description=f"Independent model id for the {ROLE_LABELS[role].lower()} role. Empty inherits the default chat model.",
            value_type="string",
            default="",
            risk="medium",
            editability="editable",
            tags=("ai", "role"),
        )
        for role in MODEL_ROLES
    ],
    _s(
        key="prompts.temperature",
        category="prompts",
        category_label="3. Prompts & agent behavior",
        label="Extraction temperature",
        description="Passed to OpenAI-compatible chat completions. Prompt bodies are versioned separately.",
        value_type="number",
        default=0,
        risk="medium",
        editability="editable",
        tags=("prompts",),
    ),
    _s(
        key="ingest.max_upload_bytes",
        category="ingestion",
        category_label="4. Document ingestion & OCR",
        label="Max upload bytes",
        description="Per-file size cap. Environment wins when MAX_UPLOAD_BYTES is set.",
        value_type="integer",
        default=50 * 1024 * 1024,
        risk="medium",
        editability="editable",
        env_key="MAX_UPLOAD_BYTES",
        tags=("ingest",),
    ),
    _s(
        key="ingest.ocr_enabled",
        category="ingestion",
        category_label="4. Document ingestion & OCR",
        label="Enable Tesseract OCR",
        description="When true, JPG/PNG run through Tesseract if the binary is present.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("ingest",),
    ),
    _s(
        key="review.preserve_verified_cells",
        category="review",
        category_label="5. Review & coding workflows",
        label="Preserve verified cells",
        description="Human-review floor. Cannot be set false. Bulk reruns skip verified cells unless the operator opts in.",
        value_type="boolean",
        default=True,
        risk="high",
        editability="readonly",
        floor=True,
        tags=("review", "floor"),
    ),
    _s(
        key="review.hot.include_flagged",
        category="review",
        category_label="5. Review & coding workflows",
        label="Hot queue includes flagged cells",
        description="Default for new tables and the global hot-queue floor.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("review", "hot"),
    ),
    _s(
        key="review.hot.include_manual",
        category="review",
        category_label="5. Review & coding workflows",
        label="Hot queue includes manual marks",
        description="Rows marked hot by a reviewer stay in the queue.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("review", "hot"),
    ),
    _s(
        key="review.citation_required_default",
        category="review",
        category_label="5. Review & coding workflows",
        label="Require citations by default",
        description="Default citation policy hint for newly created columns.",
        value_type="enum",
        default="when_quoting",
        risk="low",
        editability="editable",
        enum_options=("always", "when_quoting", "optional", "never"),
        tags=("review",),
    ),
    _s(
        key="qc.require_citation_for_complete",
        category="qc",
        category_label="6. QC & validation",
        label="QC: citation required for Complete",
        description="Advisory flag for future QC agents. Does not rewrite existing cells.",
        value_type="boolean",
        default=True,
        risk="medium",
        editability="editable",
        tags=("qc",),
    ),
    _s(
        key="users.invite_requires_admin",
        category="users",
        category_label="7. Users, roles, groups, permissions",
        label="User create requires admin",
        description="POST /api/users already requires admin. This flag is a documented floor.",
        value_type="boolean",
        default=True,
        risk="high",
        editability="readonly",
        floor=True,
        tags=("users", "floor"),
    ),
    _s(
        key="matters.default_status",
        category="matters",
        category_label="8. Matter defaults & ethical walls",
        label="Default matter status",
        description="Status assigned to newly created matters.",
        value_type="enum",
        default="open",
        risk="low",
        editability="editable",
        enum_options=("open", "hold", "closed"),
        tags=("matters",),
    ),
    _s(
        key="security.session_hours",
        category="security",
        category_label="9. Security, sessions, auth, network",
        label="Session lifetime (hours)",
        description="JWT lifetime for newly issued tokens. Existing tokens keep their original expiry.",
        value_type="integer",
        default=12,
        risk="medium",
        editability="confirm",
        tags=("security",),
    ),
    _s(
        key="security.require_auth",
        category="security",
        category_label="9. Security, sessions, auth, network",
        label="Require authentication",
        description="Security floor. Anonymous data APIs are not permitted.",
        value_type="boolean",
        default=True,
        risk="bootstrap",
        editability="readonly",
        floor=True,
        tags=("security", "floor"),
    ),
    _s(
        key="security.secret_key",
        category="security",
        category_label="9. Security, sessions, auth, network",
        label="Signing secret",
        description="Bootstrap only. Rotate offline by setting SECRET_KEY and restarting.",
        value_type="secret",
        default="",
        risk="bootstrap",
        editability="bootstrap",
        secret=True,
        env_key="SECRET_KEY",
        tags=("security", "secret"),
    ),
    _s(
        key="storage.database_url",
        category="storage",
        category_label="10. Storage, DB, vector, cache",
        label="Database URL",
        description="Bootstrap. Change DATABASE_URL and restart; not editable live.",
        value_type="string",
        default="sqlite:///./rockhawk.db",
        risk="bootstrap",
        editability="bootstrap",
        restart_required=True,
        env_key="DATABASE_URL",
        tags=("storage",),
    ),
    _s(
        key="storage.redis_url",
        category="storage",
        category_label="10. Storage, DB, vector, cache",
        label="Redis URL",
        description="Job queue. Empty uses in-process threads.",
        value_type="string",
        default="",
        risk="bootstrap",
        editability="bootstrap",
        restart_required=True,
        env_key="REDIS_URL",
        tags=("storage",),
    ),
    _s(
        key="storage.dir",
        category="storage",
        category_label="10. Storage, DB, vector, cache",
        label="Object storage directory",
        description="Filesystem path for originals. Bootstrap / restart.",
        value_type="string",
        default="./data/storage",
        risk="bootstrap",
        editability="bootstrap",
        restart_required=True,
        env_key="STORAGE_DIR",
        tags=("storage",),
    ),
    _s(
        key="jobs.concurrency",
        category="jobs",
        category_label="11. Job queues, concurrency, GPU/performance",
        label="Worker concurrency hint",
        description="Documented concurrency target. The current worker is a single pop-loop; honor this when scaling out.",
        value_type="integer",
        default=4,
        risk="medium",
        editability="editable",
        tags=("jobs",),
    ),
    _s(
        key="audit.enabled",
        category="audit",
        category_label="12. Audit, retention, legal holds, defensible deletion",
        label="Append-only audit",
        description="Audit floor. Cannot be disabled from the Administration Center.",
        value_type="boolean",
        default=True,
        risk="bootstrap",
        editability="readonly",
        floor=True,
        tags=("audit", "floor"),
    ),
    _s(
        key="audit.retention_days",
        category="audit",
        category_label="12. Audit, retention, legal holds, defensible deletion",
        label="Audit retention (days)",
        description="Advisory retention. Defensible deletion is an offline procedure; rows are never deleted by this API.",
        value_type="integer",
        default=3650,
        risk="high",
        editability="confirm",
        tags=("audit",),
    ),
    _s(
        key="notifications.escalation_email",
        category="notifications",
        category_label="13. Notifications & escalation",
        label="Escalation mailbox",
        description="Where future job-failure notices should go. SMTP delivery is still env/offline.",
        value_type="string",
        default="",
        risk="low",
        editability="editable",
        todo=True,
        tags=("notifications",),
    ),
    _s(
        key="exports.include_citations_default",
        category="exports",
        category_label="14. Exports & integrations",
        label="Include citations in exports",
        description="Default for CSV/XLSX exports of review tables.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("exports",),
    ),
    _s(
        key="backups.destination_note",
        category="backups",
        category_label="15. Backups / DR",
        label="Backup destination note",
        description="Documented destination (volume names or off-box path). No live dump from this UI.",
        value_type="string",
        default="Compose volumes: postgres_data + storage_data. Back up together.",
        risk="medium",
        editability="editable",
        todo=True,
        tags=("backups",),
    ),
    _s(
        key="observability.log_level",
        category="observability",
        category_label="16. Observability, health, maintenance",
        label="Log level",
        description="Process log level hint. Env LOG_LEVEL still wins when set.",
        value_type="enum",
        default="INFO",
        risk="low",
        editability="editable",
        enum_options=("DEBUG", "INFO", "WARNING", "ERROR"),
        env_key="LOG_LEVEL",
        tags=("observability",),
    ),
    _s(
        key="feature.ask_rockhawk",
        category="features",
        category_label="17. Feature flags",
        label="Ask RockHawk",
        description="When false, the Ask surface is hidden. Existing threads remain in audit.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("features",),
    ),
    _s(
        key="feature.hot_queue",
        category="features",
        category_label="17. Feature flags",
        label="Hot Review queue",
        description="When false, the Hot Review nav is hidden.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("features",),
    ),
    _s(
        key="feature.column_suggest",
        category="features",
        category_label="17. Feature flags",
        label="Suggest columns",
        description="Natural-language column proposals. Never auto-creates columns.",
        value_type="boolean",
        default=True,
        risk="low",
        editability="editable",
        tags=("features",),
    ),
)


REGISTRY: dict[str, SettingDef] = {item.key: item for item in SETTINGS}

CATEGORIES: list[dict[str, str]] = []
_seen: set[str] = set()
for item in SETTINGS:
    if item.category not in _seen:
        _seen.add(item.category)
        CATEGORIES.append({"id": item.category, "label": item.category_label})
CATEGORIES.append({"id": "history", "label": "18. Config revision history, import/export, approval, rollback"})


def get_definition(key: str) -> SettingDef:
    if key not in REGISTRY:
        raise KeyError(key)
    return REGISTRY[key]
